apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bualuaxua
  description: bua lua xua service supports bua lua xua things
  labels:
    tier: backend
  groups:
  - kubernetes
  - backend
  - test
spec:
  type: service
  lifecycle: staging
  owner: nguyentranbao@chotot.vn
